services:
  web:
    build: .
    ports:
      - 8080:5000
    command: "flask run --host=0.0.0.0"
    env_file:
      - .env
    networks:
      - mini-trello
    volumes:
      - ./:/app
  dynamo:
    container_name: mini-trello-db
    image: amazon/dynamodb-local
    networks:
      - mini-trello
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

networks:
  mini-trello:
    name: mini-trello

volumes:
  dynamodata: {}
